/* eslint-disable @next/next/no-page-custom-font */
export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='favicon.ico' />
      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap' rel='stylesheet' />
    </>
  );
}
