import AuthProvider from '@/app/(auth)/AuthProvider';
import ToasterProvider from '@/libs/ToastProvider';
import { AntdStyleProvider } from '@/libs/antd/AntdStyleProvider';
import ReduxProvider from '@/libs/redux/provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Santa Application',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <ReduxProvider>
            <AntdStyleProvider>{children}</AntdStyleProvider>
          </ReduxProvider>
          <ToasterProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
