import AuthProvider from '@/app/(auth)/AuthProvider';
import { AntStyleProvider } from '@/libs/antd/AntStyleProvider';
import ReduxProvider from '@/libs/redux/provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Santa Application',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <AntStyleProvider>
          <AuthProvider>
            <ReduxProvider>{children}</ReduxProvider>
          </AuthProvider>
        </AntStyleProvider>
      </body>
    </html>
  );
}
